load("//bazel:cc.bzl", "cc_library")

cc_library(
    name = "logger",
    srcs = ["logger.cc"],
    hdrs = ["logger.h"],
    deps = [
        "//bazel/external:spdlog",
    ],
    visibility = ["//visibility:public"],
)
