load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "advertisement",
    srcs = ["advertisement.cc"],
    hdrs = ["advertisement.h"],
    # visibility = [
    #   "//src/exe:__pkg__",
    #   "//util:generate_compdb",
    # ],
    visibility = ["//visibility:public"],
)
